# Generated by Django 5.2.6 on 2025-09-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_curso_nivel_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('B', 'Básico'), ('A', 'Avançado'), ('I', 'Intermediário')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('N', 'Noturno'), ('M', 'Matutino'), ('V', 'Vespertino'), ('R', 'Remoto')], default='M', max_length=3),
        ),
    ]
